# Generated by Django 4.1.7 on 2023-05-06 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.cart')),
                ('dish', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.dish')),
            ],
        ),
    ]
